#ifndef SWBT_SWITCH_SUBCOMMAND_H
#define SWBT_SWITCH_SUBCOMMAND_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#define SWBT_SWITCH_OUTPUT_REPORT_RUMBLE_AND_SUBCOMMAND 0x01u
#define SWBT_SWITCH_OUTPUT_REPORT_FW_UPDATE_PACKET 0x03u
#define SWBT_SWITCH_OUTPUT_REPORT_RUMBLE_ONLY 0x10u
#define SWBT_SWITCH_OUTPUT_REPORT_NFC_IR_MCU 0x11u
#define SWBT_SWITCH_OUTPUT_REPORT_USB_COMMAND 0x80u

#define SWBT_SWITCH_RUMBLE_DATA_SIZE 8u
#define SWBT_SWITCH_OUTPUT_RUMBLE_ONLY_SIZE 10u
#define SWBT_SWITCH_OUTPUT_SUBCOMMAND_HEADER_SIZE 11u

typedef enum {
    SWBT_SWITCH_SUBCOMMAND_STATE = 0x00,
    SWBT_SWITCH_SUBCOMMAND_MANUAL_BT_PAIRING = 0x01,
    SWBT_SWITCH_SUBCOMMAND_REQUEST_DEVICE_INFO = 0x02,
    SWBT_SWITCH_SUBCOMMAND_SET_REPORT_MODE = 0x03,
    SWBT_SWITCH_SUBCOMMAND_TRIGGER_BUTTONS_ELAPSED = 0x04,
    SWBT_SWITCH_SUBCOMMAND_GET_PAGE_LIST_STATE = 0x05,
    SWBT_SWITCH_SUBCOMMAND_SET_HCI_STATE = 0x06,
    SWBT_SWITCH_SUBCOMMAND_RESET_PAIRING_INFO = 0x07,
    SWBT_SWITCH_SUBCOMMAND_LOW_POWER_MODE = 0x08,
    SWBT_SWITCH_SUBCOMMAND_SPI_FLASH_READ = 0x10,
    SWBT_SWITCH_SUBCOMMAND_SPI_FLASH_WRITE = 0x11,
    SWBT_SWITCH_SUBCOMMAND_RESET_MCU = 0x20,
    SWBT_SWITCH_SUBCOMMAND_SET_MCU_CONFIG = 0x21,
    SWBT_SWITCH_SUBCOMMAND_SET_MCU_STATE = 0x22,
    SWBT_SWITCH_SUBCOMMAND_SET_PLAYER_LIGHTS = 0x30,
    SWBT_SWITCH_SUBCOMMAND_GET_PLAYER_LIGHTS = 0x31,
    SWBT_SWITCH_SUBCOMMAND_SET_HOME_LIGHT = 0x38,
    SWBT_SWITCH_SUBCOMMAND_ENABLE_IMU = 0x40,
    SWBT_SWITCH_SUBCOMMAND_SET_IMU_SENSITIVITY = 0x41,
    SWBT_SWITCH_SUBCOMMAND_WRITE_IMU_REGISTER = 0x42,
    SWBT_SWITCH_SUBCOMMAND_READ_IMU_REGISTER = 0x43,
    SWBT_SWITCH_SUBCOMMAND_ENABLE_VIBRATION = 0x48,
    SWBT_SWITCH_SUBCOMMAND_GET_REGULATED_VOLTAGE = 0x50,
} swbt_switch_subcommand_id_t;

typedef enum {
    SWBT_SWITCH_SUBCOMMAND_OK = 0,
    SWBT_SWITCH_SUBCOMMAND_ERROR_INVALID_ARGUMENT = -1,
    SWBT_SWITCH_SUBCOMMAND_ERROR_PACKET_TOO_SHORT = -2,
    SWBT_SWITCH_SUBCOMMAND_ERROR_UNSUPPORTED_REPORT_ID = -3,
} swbt_switch_subcommand_result_t;

typedef struct {
    uint8_t output_report_id;
    uint8_t packet_counter;
    uint8_t rumble[SWBT_SWITCH_RUMBLE_DATA_SIZE];
    bool has_subcommand;
    uint8_t subcommand_id;
    const uint8_t *subcommand_data;
    size_t subcommand_data_len;
} swbt_switch_output_report_t;

swbt_switch_subcommand_result_t
swbt_switch_parse_output_report(const uint8_t *data, size_t data_len,
                                swbt_switch_output_report_t *out_report);

bool swbt_switch_subcommand_is_known(uint8_t subcommand_id);

#endif
