function(swbt_apply_sanitizers target_name)
    if(MSVC)
        return()
    endif()

    set(swbt_sanitizers "")
    if(SWBT_ENABLE_ASAN)
        list(APPEND swbt_sanitizers address)
    endif()
    if(SWBT_ENABLE_UBSAN)
        list(APPEND swbt_sanitizers undefined)
    endif()

    if(swbt_sanitizers)
        list(JOIN swbt_sanitizers "," swbt_sanitizer_arg)
        target_compile_options(${target_name} PRIVATE "-fsanitize=${swbt_sanitizer_arg}" -fno-omit-frame-pointer)
        target_link_options(${target_name} PRIVATE "-fsanitize=${swbt_sanitizer_arg}")
    endif()
endfunction()
