name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Verify in Dev Container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: just verify-ci
